### ISSUE TITLE
"Add to Chrome" is disabled on https://chromewebstore.google.com

### ISSUE THREAD

**Issue by ben-page** [NeverDecaf/chromium-web-store#139] opened 2024-01-03 18:53 UTC
Looks like something changed on the store again.

1. Navigate to any extension. For example, https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
2. "Add to Chrome" is disabled. Red banner says "Item currently unavailable. Please check the troubleshooting guide."

Version 1.5.4

**Comment by ben-page** [comment] 2024-01-03 18:56
Seems to be related to #135 

Refreshing the page as needed will fix the button.

**Comment by NeverDecaf** [comment] 2024-01-14 21:28
Correct, this is a duplicate of 135.

**Closed by NeverDecaf** 2024-01-14 21:28 UTC
